--CREATE TABLE mama_survey (
--id serial primary key,
--phone varchar(20),
--location varchar(20),
--age integer,
--famPlan varchar(7),
--hiv varchar(7),
--parity integer,
--dueDate date,
--completed BOOLEAN NOT NULL DEFAULT FALSE
--)